pipeline {
    agent any

    stages {
        stage('Git') {
            steps {
                git branch: 'main', url: 'https://github.com/maximbabenko/ML_labs.git'
            }
        }
        stage('Environment preparation') {
            steps {
                echo "Installing Dependencies (begin)"
                sh 'pip install -r ./lab2/requirements.txt'
                echo "Installing Dependencies (end)"
            }
        }
        stage('Data Creation') {
            steps {
                echo "Create Dataset (begin)"
                sh 'python ./lab2/create_dataset.py'
                echo "Create Dataset (end)"
            }
        }
        stage('Data Preprocessing') {
            steps {
                echo "Data Preprocessing (begin)"
                sh 'python ./lab2/data_preprocessing.py'
                echo "Data Preprocessing (end)"
            }
        }
        stage('Train Model') {
            steps {
                echo "Training model (begin)"
                sh 'python ./lab2/model_training.py'
                echo "Training model (end)"
            }
        }
        stage('Test Model') {
            steps {
                echo "Testing model (begin)"
                sh 'python ./lab2/model_testing.py'
                echo "Testing model (end)"
            }
        }

    }
}